# Generated by Django 6.0 on 2025-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewYear', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='l2_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='l2_departments',
            field=models.ManyToManyField(blank=True, related_name='l2_managers', to='NewYear.department'),
        ),
    ]
