# Generated by Django 6.0 on 2025-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewYear', '0003_remove_user_l2_manager_user_l2_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalrecord',
            name='l1_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
